config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'groups#index'
  resources :users, only: [:edit, :update, :index]
  resources :groups, only: [:new, :create, :edit, :update] do
    resources :messages, only: [:index, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :members
  has_many :users, through: :members
  has_many :messages
  validates :name, presence: true
  def show_last_message
    if (last_message = messages.last).present?
      last_message.body? ? last_message.body : '画像が投稿されています'
    else
      'まだメッセージはありません。'
    end
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :group
  belongs_to :user
  validates :body, presence: true, unless: :image?
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :members
  has_many :groups, through: :members
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_group

  def index
    @message = Message.new
    @messages = @group.messages.includes(:user)
      respond_to do |format|
        format.html
        format.json
      end
  end

  def create
    @message = @group.messages.new(message_params)
    if @message.save
      respond_to do |format|
        format.html { redirect_to group_messages_path(@group)}
        format.json
      end
    else
      @messages = @group.messages.includes(:user)
      flash.now[:alert] = 'メッセージを入力してください。'
      render :index
    end
  end


  private
  def message_params
    params.require(:message).permit(:body, :image).merge(user_id: current_user.id)
  end

  def set_group
    @group = Group.find(params[:group_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.where('name LIKE(?)', "#{params[:keyword]}%")
    respond_to do |format|
      format.html
      format.json
    end
  end
  def edit

  end
  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_form.html.haml
= form_for group do |f|
  - if group.errors.any?
    .chat-group-form__errors
      %h2= "#{group.errors.full_messages.count}件のエラーが発生しました。"
      %ul
        - group.errors.full_messages.each do |message|
          %li= message
  .chat-group-form__field
    .chat-group-form__field--left
      = f.label :グループ名, class: 'chat-group-form__label'
    .chat-group-form__field--right
      = f.text_field :name, class: 'chat__group_name chat-group-form__input', placeholder: 'グループ名を入力してください'
  .chat-group-form__field.clearfix
    / この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します
    .chat-group-form__field--left
      %label.chat-group-form__label{for: "chat_group_チャットメンバーを追加"} チャットメンバーを追加
    .chat-group-form__field--right
      .chat-group-form__search.clearfix
        %input#user-search-field.chat-group-form__input{placeholder: "追加したいユーザー名を入力してください", type: "text"}/
      #user-search-result
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label{for: "chat_group_チャットメンバー"} チャットメンバー
    .chat-group-form__field--right
      / グループ作成機能の追加時はここにcollection_check_boxesの記述を入れてください
      / = f.collection_check_boxes :user_ids, User.all, :id, :name
      / この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します
      #chat-group-users
        - group.users.each do |user|
          #chat-group-user-22.chat-group-user.clearfix
            = f.hidden_field :member, name: 'group[user_ids][]', value: user.id
            %p.chat-group-user__name
              = user.name
            %a.user-search-remove.chat-group-user__btn.chat-group-user__btn--remove.js-remove-btn 削除
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field--right
      = f.submit class: 'chat-group-form__action-btn'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ChatSpace
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = yield

app/views/messages/_left-side.html.haml
.left-side
  .left-side__top-bar
    .left-side__top-bar__user-name= current_user.name
    =link_to new_group_path, class: "left-side__top-bar__create-group" do
      =fa_icon "edit"
    =link_to edit_user_path(current_user), class: "left-side__top-bar__user-setting" do
      =fa_icon "cog"
  .left-side__bottom-bar
    - current_user.groups.each do |group|
      .left-side__bottom-bar__group
        = link_to group_messages_path(group) do
          .left-side__bottom-bar__group__name
            = group.name
          .left-side__bottom-bar__group__message
            = group.show_last_message

app/views/messages/_message.html.haml
.right-main__chat-main__message{ "data-message-id": "#{message.id}"}
  .right-main__chat-main__message__name
    = message.user.name
  .right-main__chat-main__message__time
    = message.created_at
  .right-main__chat-main__message__body
    - if message.body.present?
      = message.body
    - else
      = image_tag message.image, class: "right-main__chat-main__message__image"

app/views/messages/_right-main.html.haml
.right-main
  .right-main__header-bar
    .right-main__header-bar__group-name
      = @group.name
    = link_to "edit", edit_group_path(@group), class: "right-main__header-bar__edit-btn"
    .right-main__header-bar__group-members
      Members:
      - @group.users.each do |users|
        = users.name
  .right-main__chat-main
    = render partial: 'message', collection: @messages
  .right-main__footer
    = form_for [@group, @message], {html: {id: "js-form"}} do |f|
      .right-main__footer__form
        .right-main__footer__form__body
          = f.text_field :body, class: 'right-main__footer__form__body__message', placeholder: "type a message"
          = f.label :image, class: "right-main__footer__form__body__label" do
            %span.right-main__footer__form__body__label__span
              =fa_icon "image"
            = f.file_field :image, class: "right-main__footer__form__body__label__input"
          = f.submit 'Send', class: 'right-main__footer__form__body__submit'

app/views/messages/index.html.haml
= render partial: "left-side", object: @group
= render partial: "right-main", object: @group, object: @message, object: @messages